ifndef::imagesdir[:imagesdir: ../images]

[[section-introduction-and-goals]]
==	Einführung und Ziele

ifdef::arc42help[]
[role="arc42help"]
****
Beschreibt die wesentlichen Anforderungen und treibenden Kräfte, die bei der Umsetzung der Softwarearchitektur und Entwicklung des Systems berücksichtigt werden müssen.

Dazu gehören:

* zugrunde liegende Geschäftsziele,
* wesentliche Aufgabenstellungen,
* wesentliche funktionale Anforderungen,
* Qualitätsziele für die Architektur und
* relevante Stakeholder und deren Erwartungshaltung.
****
endif::arc42help[]

=== Aufgabenstellung

==== User Story 1: Anmelden Technologie-Radar-Administration (Prio 'Could')

Als CTO oder Tech-Lead kann ich mich an der Technologie-Radar-Administration anmelden, damit ich Technologien im Technologie-Radar verwalten kann.

**Akzeptanzkriterien**

* Mittels korrektem Benutzername (E-Mail Adresse) und korrektem Passwort gelange ich zur Technologie-Radar-Administration.
* Mit nicht korrekten Benutzerdaten (Benutzername / Passwort) kann ich mich nicht anmelden.
* Nur Personen mit der Rolle CTO oder Tech-Lead dürfen sich in der Administration anmelden.

==== User Story 2: Technologie erfassen (Prio 'Must')

Als CTO kann ich eine neue Technologie erfassen, damit ich diese anschliessend publizieren kann.

**Akzeptanzkriterien**

* Für die Erfassung einer neuen Technologie muss ich folgende Felder angeben können:
** Name (Muss-Feld) -> z.B. *ArgoCD*
** Kategorie (Muss-Feld) -> z.B. *Tools*
** Ring (Muss-Feld) -> z.B. *Trial*
** Beschreibung Technologie (Muss-Feld) -> z.B. *Argo CD is a declarative, GitOps continuous delivery tool for Kubernetes.*
** Beschreibung der Einordnung (Muss-Feld) -> z.B. *Without making a judgment of the GitOps technique, we'd like to talk about Argo CD within the scope of deploying and monitoring applications in Kubernetes environments...*
* Sofern ein Muss-Feld nicht abgefüllt ist, darf die Technologie nicht abgespeichert werden.
* Neben den Eingaben müssen folgende Informationen bei der Erfassung einer neuen Technologie hinterlegt werden
** Erfassungsdatum

==== User Story 3: Technologie entwerfen und später publizieren (Prio 'Should')

Als CTO kann ich erfasste, aber noch nicht publizierte, Technologien publizieren, damit diese auf dem Technologie-Radar erscheinen und entsprechned für Mitarbeiter einsehbar werden.

**Akzeptanzkriterien**

* Erfasste, aber noch nicht publizierte Technologien werden speziell gekennzeichnet.
* Für Entwürfe dürfen folgende Pflichtfelder leer sein:
** Einordnung / Ring
** Beschreibung der Einordnung
* Mit Klick auf *Publizieren* werden neue Technologien publiziert. Bei der Publizierung müssen folgende Eingaben gemacht werden:
** Einordnung / Ring (Muss-Feld) -> z.B. *Trial*
** Beschreibung der Einordnung (Muss-Feld) -> z.B. *Without making a judgment of the GitOps technique, we'd like to talk about Argo CD within the scope of deploying and monitoring applications in Kubernetes environments...*
* Neben den Eingaben müssen folgende Informationen bei der Publikation einer Technologie hinterlegt werden
** Publikationsdatum.

==== User Story 4: Technologie ändern (Prio 'Should')

Als CTO kann ich erfasste Technologien ändern, um z.B. fehlerhafte Daten oder nicht mehr passende Informationen zu ändern.

**Akzeptanzkriterien**

* Folgende Felder können geändert werden:
** Name (Muss-Feld)
** Kategorie (Muss-Feld)
** Beschreibung Technologie (Muss-Feld)
* Mit dem Speichern wird das Änderungsdatum der Technologie hinterlegt.

==== User Story 5: Technologie-Einordnung ändern (Prio 'Should')

Als CTO möchte ich die Einordnung von einer Technologie ändern, um die Relevanz der Technologie für das Unternehmen anders einstufen zu können.

**Akzeptanzkriterien**

* Mit Klick auf "Einordnung ändern", können folgende Felder einer Technologie geändert werden:
** Einordnung / Ring (Muss-Feld) -> z.B. *Adopt*
** Beschreibung der neuen Einordnung (Muss-Feld)
* Mit dem Speichern wird das Änderungsdatum der Technologie hinterlegt.

==== User Story 6: Technologien anzeigen (Prio 'Must')

Als Mitarbeiter kann ich im Technologie-Radar-Viewer die Technologien resp. der Technologie-Radar einsehen.

**Akzeptanzkriterien**

* Es werden nur publizierte Technologien angezeigt.
* Technologien werden nach ihren Kategorien (*Techniques*, *Platforms*, *Tools*, *Languages & Frameworks*) strukturiert.
* Technologien werden nach ihrer Maturität (*Assess*, *Trial*, *Adopt*, *Hold*) strukturiert.

**Bemerkung**: Die Technologien müssen nicht als *Radar* abgebildet werden, sondern können auch tabellarisch dargestellt werden.

==== User Story 7: Anmelden am Technologie-Radar-Viewer (Prio 'Could')

Als Mitarbeiter kann ich mich am Technologie-Radar-Viewer anmelden, damit ich die Technologien resp. der Technologie-Radar des Unternehmens einsehen kann.

**Akzeptanzkriterien**

* Mittels korrektem Benutzername (E-Mail Adresse) und korrektem Passwort gelange ich zum Technologie-Radar-Viewer.
* Mit nicht korrekten Benutzerdaten (Benutzername / Passwort) kann ich mich nicht anmelden.

=== Qualitätsziele

* Der **Technologie-Radar-Viewer** soll neben der Desktop-Ansicht, auch für die Mobile/Tablet-Ansicht optimiert sein.
* Der **Technologie-Radar-Viewer** soll bei einer 4G-Verbindung innerhalb 1s geladen werden.
** Chrome Network-Throttling: _Fast 4G_ https://github.com/ChromeDevTools/devtools-frontend/blob/817e20b1b51181ddc1da58c5b339c6eaf34b16cd/front_end/core/sdk/NetworkManager.ts#L452[Details]
** Others: 9 Mbit/s down, 1.5 Mbit/s up, 60ms Latency, 0% Package-Loss
* Sämtliche Anmeldungen an die **Technologie-Radar-Administration** werden aufgezeichnet.
* Die Funktionalitäten sollen mittels sinnvollen automatisierten **Unit/Integration-Tests** überprüft werden.

=== Stakeholder

ifdef::arc42help[]
[role="arc42help"]
****
.Inhalt
Expliziter Überblick über die Stakeholder des Systems – über alle Personen, Rollen oder Organisationen –, die

* die Architektur kennen sollten oder
* von der Architektur überzeugt werden müssen,
* mit der Architektur oder dem Code arbeiten (z.B. Schnittstellen nutzen),
* die Dokumentation der Architektur für ihre eigene Arbeit benötigen,
* Entscheidungen über das System und dessen Entwicklung treffen.

.Motivation
Sie sollten die Projektbeteiligten und -betroffenen kennen, sonst erleben Sie später im Entwicklungsprozess Überraschungen.
Diese Stakeholder bestimmen unter anderem Umfang und Detaillierungsgrad der von Ihnen zu leistenden Arbeit und Ergebnisse.

.Form
Tabelle mit Rollen- oder Personennamen, sowie deren Erwartungshaltung bezüglich der Architektur und deren Dokumentation.
****
endif::arc42help[]

[cols="1,1,2" options="header"]
|===
|Rolle |Kontakt |Erwartungshaltung
| Auftraggeber | Dominik Witschard | _<Erwartung-1>_
| Entwickler | Mathias Vogel | _<Erwartung-2>_
|===
