ifndef::imagesdir[:imagesdir: ../images]

[[section-design-decisions]]
== Fazit

Auf das Projekt habe ich mich sehr gefreut, um das gelernte Wissen aus dem Modul umzusetzen. Es hat mir sehr viel Spass gemacht, die Applikation zu entwickeln und die Architektur zu gestalten. Anfangs dachte ich, das Ganze wird sicher in den definierten 60 Stunden gut machbar sein, aber leider musste ich schnell feststellen, dass es doch deutlich mehr Zeit in Anspruch genommen hat.

*Herausforderungen beim Technologie-Setup*

Für das Projekt nahm ich den Vorschlag vom Dozenten an und dachte mir, dass ich noch einige coole Technologien verwenden könnte. Leider führte das dazu, dass ich beim Aufsetzen einzelner Technologien viel länger gebraucht habe, als mir lieb war. Dies führte dazu, dass ich nun einiges mehr an Stunden angesammelt habe als geplant.

Ein konkretes Beispiel war Prisma, welches vor kurzem auf die Version 7 erhöht wurde. Da die Version brandneu war, gab es Probleme mit dem IntelliJ-Plugin. Die Fehlersuche hat mich mehrere Stunden gekostet, bis ich herausfand, dass ich den prisma/language-server@7.0.0 manuell installieren und konfigurieren musste.

Allgemein muss ich sagen, dass das Aufsetzen der verschiedenen Technologien deutlich mehr Zeit braucht als gedacht. Die Dokumentationen sind oft nicht mehr aktuell oder man findet Fehler, für welche es keine beschriebenen Lösungen gibt. Das Ganze hat mich ab und zu schon ein wenig gebrochen, wenn man sehr lange daran sitzt und das Gefühl hat, es geht nicht voran. Am Ende konnte ich dann trotzdem meistens alles sauber aufsetzen.

*Umsetzung der Anforderungen und Testing*

Nachdem das Grundgerüst stand, ging eigentlich alles sehr „straight forward“. Das Bauen der Endpunkte und des Frontends ging relativ zügig. Einzig das Formular für die Technologien, bei welchem ich alles in einem haben wollte (create, update), gab ein wenig mehr Arbeit.

Beim Thema Testing war Cypress eine positive Überraschung. Es ist sehr angenehm damit zu arbeiten, weshalb ich am Ende deutlich mehr E2E-Tests geschrieben habe als ursprünglich geplant. Ich bin ehrlich gesagt kein grosser Fan davon, Unit-Tests zu schreiben, bei denen man für jede Kleinigkeit 100 Abhängigkeiten mocken muss – da bieten E2E-Tests für mich einen viel grösseren Mehrwert, um die echten User Stories abzusichern.

*Zukunft*

Allgemein kann ich sagen, dass mir die Arbeit mit Angular sehr viel Spass gemacht hat, obwohl ich davor eher mit React gearbeitet habe. Und ich denke, ich werde Angular in Zukunft auch weiter verwenden, da es einfach sehr angenehm ist damit zu arbeiten. Es gibt viele coole Features und es ist sehr gut dokumentiert.